name: cdk-version

on:
  push:
    branches: [ main ]

jobs:
   deploy:
     runs-on: ubuntu-latest

     steps:
       - name: cdk help
         run: cdktf help

       - name: cdktf version
         run: cdktf --version
