name: terraform-cdk-version

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
#      - uses: actions/checkout@v2

      - name: cdk help
        run: cdktf help

      - name: cdktf version
        run: cdktf --version
