name: terraform-cdk-version

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: sdk help
        run: sdktf help
